navigation:
  - title: Products
    url: /products/index.html
  - title: Pricing<span> & Signup</span>
    url: /pricing/index.html
  - title: Customers
    url: /customers/index.html

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:title
site_url: 'http://www..donde.io'
exclude: ['Rakefile', 'README.md', 'config.rb']
github:
username: dev@donde.io
