navigation:
  - title: Products
    url: /products
  - title: Pricing<span> & Signup</span>
    url: /pricing
  - title: Customers
    url: /customers

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:title
site_url: 'http://www..donde.io'
exclude: ['Rakefile', 'README.md', 'config.rb', 's3_website.yml', 'segment.html']
github:
username: dev@donde.io
